navikt/familie-felles-frontend

- packages/familie-backend/lib/auth/session.ts
- packages/familie-backend/lib/backend.ts
- packages/familie-backend/lib/typer.ts
Mindre opprydding.
affects: @navikt/familie-backend
> feat(backend): eksponerer logging.

- packages/familie-backend/README.md
affects: @navikt/familie-backend
> docs(backend): skriver om dokumentasjonen til å være tilpasset ny service modell.

- packages/familie-backend/lib/auth/session.ts
- packages/familie-backend/lib/backend.ts
- packages/familie-backend/lib/metrikker.ts
- packages/familie-backend/lib/router.ts
affects: @navikt/familie-backend
Har også gjort mindre justeringer på sesjonconfig.
> feat(backend): legger til promethues før sesjonen konfigureres.

- packages/familie-backend/lib/auth/token.ts
Slik at de henger sammen med selve tokenet på samme scope.
> Fikser feil i expiry på tokens 

- packages/familie-clipboard/clipboard.stories.tsx
- packages/familie-ikoner/ikoner.stories.tsx
- packages/familie-ikoner/src/familie/FamilieIkonVelger.tsx
- packages/familie-typer/src/personTyper.ts
- packages/familie-visittkort/src/index.tsx
- packages/familie-visittkort/visittkort.stories.tsx
- packages/introduksjon.stories.mdx
- tsconfig.base.json
legger til og forbedrer dokumentasjon til eksisterende komponen
affects: @navikt/familie-clipboard, @navikt/familie-ikoner, @navikt/familie-typer,
@navikt/familie-visittkort
> docs(clipboard, ikoner, visittkort)

- packages/familie-clipboard/package.json
- yarn.lock
Fix the master branch workflow fail
> fix storybook deploy

- packages/familie-backend/src/auth/session.ts
slik at alle som sender inn en url til redis bruker redis for caching av session.
> Endrer config for e2e

- .github/workflows/build_master.yaml
This is an issue with lerna, which I have fixed for branch build
> fix build script

- package.json
- packages/familie-backend/README.md
- packages/familie-backend/src/auth/authenticate.ts
- packages/familie-backend/src/auth/azure/azure.ts
- packages/familie-backend/src/auth/utils.ts
- packages/familie-backend/src/config.ts
- packages/familie-backend/src/logging.ts
Begynt på noe debug logging som kan være nyttig ved behov.
> Legger til fornying av tokenset for self for å unngå utlogging etter 1 time.

- packages/familie-backend/package.json
- yarn.lock
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44822
> Fjerner @types/moment-timezone for å kunne bygge

- packages/familie-header/src/søk/Søk.tsx
- Gjør søk mer tolerant ved å ta høyde for at det kan komme tekstsøk
- Trim ble ikke trigga ved paste, men det skjer nå
> Småfiks på søk

- packages/familie-form-elements/src/textarea/FamilieTextarea.tsx
- yarn.lock
> perf: legg til disabled prop på TextArea

- packages/familie-sprakvelger/tsconfig.json
> fix(Tsconfig): fiks dist struktur i tsconfig

- packages/familie-form-elements/package.json
- packages/familie-form-elements/src/radiogruppe/FamilieRadioGruppe.tsx
- packages/familie-form-elements/src/skjultLabel/SkjultLabel.tsx
- packages/familie-form-elements/src/skjultLabel/skjultLabel.stories.tsx
> fix(Skjult label eksport): fiks feilmelding som kom pga. deafult eksport

- packages/familie-form-elements/src/index.ts
- packages/familie-form-elements/src/ja-nei-spørsmål/JaNeiSpørsmål.tsx
- packages/familie-form-elements/src/ja-nei-spørsmål/index.ts
- packages/familie-form-elements/src/ja-nei-spørsmål/jaNeiSpørsmål.stories.tsx
- packages/familie-form-elements/src/ja-nei-spørsmål/typer.ts
> feat(ja-nei-komponent): ja-nei-komponent med oppfølging

- packages/familie-skjema/src/felt.ts
affects: @navikt/familie-skjema
> chore(familie-skjema): fjernet en kommentar for eslint i Felt.ts

- packages/familie-skjema/skjema.stories.tsx
- packages/familie-skjema/src/typer.ts
affects: @navikt/familie-skjema
> fix(familie-skjema): støtte select-elementer i FeltOnChange

- .storybook/main.js
- packages/familie-form-elements/package.json
- packages/familie-form-elements/src/ja-nei-spørsmål/JaNeiSpørsmål.tsx
- packages/familie-form-elements/src/ja-nei-spørsmål/jaNeiSpørsmål.stories.tsx
- yarn.lock
Ja/Nei-knapper legger seg nå under hverandre. La på en knob i story for å tweake bredde.
Ser ut som mye endringer i yarn.lock, men eneste jeg har lagt til er storybook knobs som dev dependency i form elements, en pakke som allerede var i workspace yarn.lock fra før.
> fix(familie-form-elements): endre ja/nei-spm til å være vertikal

- packages/familie-form-elements/src/index.ts
- packages/familie-form-elements/src/måned-år-velger/MånedVelger.tsx
- packages/familie-form-elements/src/måned-år-velger/MånedÅrVelger.tsx
- packages/familie-form-elements/src/måned-år-velger/index.ts
- packages/familie-form-elements/src/måned-år-velger/maaned-aar-velger.stories.tsx
- packages/familie-form-elements/src/måned-år-velger/ÅrVelger.tsx
Forsøker å legge inn måned-år-velgeren som EF bruker i sin saksbehandlingsløsning til felles. Usikker på om jeg har "husket" alt for at dette skal fungere...
> Legg inn måned-år-velger som to select-valg i felles

- packages/familie-sprakvelger/src/Sprakvelger.tsx
> fix(Chevron klikkbar): gjør chevron klikkbar i språkvelgeren

- packages/familie-sprakvelger/package.json
> fix(sprakvelger): bruk intl peerDependency istedenfor egen

- packages/familie-visittkort/src/index.tsx
Dette trengs for å løse [denne](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-4293) oppgaven i `familie-ef-sak-frontend`.
> Legg til muligheten til å legge til lenke på Visittkort

- packages/familie-sprakvelger/package.json
- yarn.lock
Bump alle språkvelger-dependencies, inkludert nav-frontend-typografi-style slik at denne kan bumpes i søknadsdialogen også
> (deps) Bump alle språkvelger-dependencies

- packages/familie-endringslogg/src/endringslogg-container.tsx
- packages/familie-endringslogg/src/index.tsx
affects: @navikt/familie-endringslogg
> feat(Endringslogg): lagt inn støtte for intervallbasert datauthenting

- packages/familie-tidslinje/Tidslinje.stories.tsx
- packages/familie-tidslinje/TidslinjeMedIkon.stories.tsx
- packages/familie-tidslinje/package.json
- packages/familie-tidslinje/src/components/tidslinje/AktivtUtsnitt.tsx
- packages/familie-tidslinje/src/components/tidslinje/Tidslinje.tsx
- packages/familie-tidslinje/src/components/tidslinje/TimelineRow.tsx
- packages/familie-tidslinje/src/index.ts
affects: @navikt/familie-tidslinje
> fix(tidslinje): kopierte aktivtUtsnitt-funkjsjonalitet fra helse-frontend-tidslinje

- packages/familie-visittkort/src/index.tsx
Vil brukes i famile-ba-sak til å sette eget ikon for saker som gjelder institusjon
> Utvider Visittkort med valgfritt ikon-argument

- packages/familie-backend/package.json
- yarn.lock
Tror ikke det skal være noen endringer i versjonen som påvirker oss, men er ikke 100% sikker. Får testet det når jeg drar inn den nye pakken her i ba-sak-frontend
> Oppgrader passport

- packages/familie-visittkort/src/index.tsx
affects: @navikt/familie-visittkort
> fix(visittkort): sender med klassenavn så style kan overskrives

- .github/workflows/build_branch.yaml
- package.json
Siden jeg nå har klart å brekke storybooken i master to ganger tenker jeg at dette er lurt å ha! 😄
> chore: brekk PR-bygg dersom storybook ikke kan bygges

- packages/familie-form-elements/src/checkbox/checkbox.stories.tsx
- packages/familie-form-elements/src/checkboxgroup/FamilieCheckboxGroup.tsx
- packages/familie-form-elements/src/checkboxgroup/checkboxgroup.stories.tsx
- packages/familie-form-elements/src/checkboxgroup/index.ts
- packages/familie-form-elements/src/index.ts
...med lesevisning 🤓 
Skjermbilder:
> feat(familie-form-elements): legg til FamilieCheckboxGroup 

- komponent/src/index.tsx
- packages/familie-sprakvelger/src/SprakContext.tsx
- packages/familie-visittkort/src/index.tsx
affects: @navikt/familie-sprakvelger, @navikt/familie-visittkort
Fikser for å fikse bygget til https://github.com/navikt/familie-felles-frontend/pull/591
> chore(visittkort, språkvelger): legger til children som props

- packages/familie-dokumentliste/package.json
- yarn.lock
affects: @navikt/familie-dokumentliste
BREAKING CHANGE:
Oppgradering av designsystem
> chore(dokumentliste): oppgraderer til versjon 1 av designsytemet

- packages/familie-tidslinje/package.json
- packages/familie-tidslinje/src/components/tidslinje/AktivtUtsnitt.tsx
- packages/familie-tidslinje/src/components/tidslinje/AxisLabels.tsx
- packages/familie-tidslinje/src/components/tidslinje/Pins.tsx
- packages/familie-tidslinje/src/components/tidslinje/Tidslinje.tsx
- packages/familie-tidslinje/src/components/tidslinje/TimelineRow.tsx
- packages/familie-tidslinje/src/components/tidslinje/Tooltip.tsx
- yarn.lock
affects: @navikt/familie-tidslinje
Oppdaterte ds-pakker til å fylgje form-elements, header o.s.b. Tatt i bruk ds-tokens i nokon av komponentane.
> chore(tidslinje): oppdaterte ds-pakker og tatt i bruk ds-tokens i familie-tidslinje

- .github/dependabot.yml
- .github/workflows/build_branch.yaml
- .github/workflows/build_master.yaml
- .github/workflows/codeql-analysis.yml
Kommentar:
Slik jeg tolker det burde man ikke trenge denne med checkout v2/v3, men valgte å ikke slette den nå
```
- name: Prepare repository
run: git checkout "${GITHUB_REF:11}"
```
> Oppdaterer github action og legger til cache

- packages/familie-backend/src/utils.ts
https://logs.adeo.no/goto/96e3c5c0-5f9c-11ed-9e2b-0f22a81fd3e1
> Logger requestId

- .gitignore
- packages/familie-clipboard/package.json
- packages/familie-clipboard/src/types/react.d.ts
- packages/familie-dokumentliste/package.json
- packages/familie-endringslogg/package.json
- packages/familie-endringslogg/src/types/react.d.ts
- packages/familie-form-elements/package.json
- packages/familie-header/package.json
- packages/familie-header/src/types/react.d.ts
- packages/familie-sprakvelger/package.json
- packages/familie-sprakvelger/src/types/react.d.ts
- packages/familie-tidslinje/package.json
- packages/familie-visittkort/package.json
- yarn.lock
affects: @navikt/familie-clipboard, @navikt/familie-dokumentliste, @navikt/familie-endringslogg, @navikt/familie-form-elements, @navikt/familie-header, @navikt/familie-sprakvelger, @navikt/familie-tidslinje, @navikt/familie-visittkort
> feat: tillat alle v2-minors av @navikt/ds-pakker

- packages/familie-skjema/src/skjema.ts
- packages/familie-skjema/src/typer.ts
affects: @navikt/familie-skjema
> Lagt til eksportert type for return-verdien til useSkjema

- packages/familie-endringslogg/package.json
- packages/familie-endringslogg/src/chevron-lenke/chevron-lenke.tsx
- packages/familie-endringslogg/src/endringslogg-content.tsx
- packages/familie-endringslogg/src/modal/tour-modal/tour-modal.tsx
- yarn.lock
Breaking ettersom ds-icons er byttet ut med aksel-icons.
> Oppgradere nav-biblioteker for familie-endringslogg.

- .github/dependabot.yml
Fikser at storybook ikke kom med i den andre storybook-grupperingen. Grupperer også commitlint
> Grupper storybook og commitlint

- lerna.json
- package.json
- yarn.lock
Har oppdatert lerna og andre generelle avhengigheter
> chore(generell): oppgradering av generelle avhengigheter

- packages/familie-backend/src/auth/session.ts
- packages/familie-backend/src/index.ts
- packages/familie-backend/src/utils.ts
+ kaster feil hvis vi ikke klarer å koble oss på etter 100 forsøk
> Redis øker default reconnect forsøk 

- packages/familie-typer/src/journalføring.ts
Prerekvisitt for visning av adresse brev er sendt til fra familie-ba-sak-frontend
> Utvider IJournalpost med utsendingsinfo

- packages/familie-http/package.json
BREAKING CHANGE: Oppgraderer axios fra v0 til v1
> feat(familie-http): oppdaterer til axios v1 i familie-http

- README.md
Lagt til tekst om at branch må opprettes før man kjører yarn ct
> docs(readme): oppdatert readme

- packages/familie-header/header.stories.tsx
- packages/familie-header/src/header/Header.tsx
lenker med onClick istedet for href skal også kunne vises med ikoner
> fix(header.tsx): lenker med onClick skal også kunne vises med ikoner

- .husky/pre-commit
- package.json
- packages/familie-tidslinje/package.json
- packages/familie-tidslinje/src/components/tidslinje/calc.test.ts
- packages/familie-tidslinje/src/components/tidslinje/filter.test.ts
- packages/familie-tidslinje/src/components/tidslinje/sort.test.ts
- packages/familie-tidslinje/vitest.config.ts
- yarn.lock
Bumper major dependencies, noen få av gangen. Legger til husky slik at lint-staged kjører. Endrer fra jest til vitest. ☺️
> Oppdater dependencies, erstatter jest med vitest

- .github/workflows/build_branch.yaml
- .github/workflows/build_master.yaml
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-20789
Endrer til å bygge med Node v24.
> Node v22 -> v24
