packages/familie-header/header.stories.tsx
packages/familie-header/headerstories.less
packages/familie-header/src/header/Header.tsx

Etter avtale med Tone (EF) og Gunn (BA) ble vi enige om at Enhet ikke er en nødvendig opplysning å ha med i headeren, men saksbehandlere ønsker fremdeles å ha den inntil videre i BA.

refactor!: Endre "enhet" i header til å kun vises dersom den sendes inn

---

packages/familie-form-elements/src/datovelger/FamilieDatovelger.tsx

Datepickeren importerer uansett den less-filen internt så vi skaper bare krøll ved å importere den her.

(chore) Fjern unødvendig import av css som skaper konflikt med jest

---

packages/familie-skjema/src/typer.ts
packages/familie-skjema/src/validators.ts

affects: @navikt/familie-skjema
Refaktorer feilmeldingsfeltet i felt-hook til å være en reactNode i stedet for string

fix(Refaktor felthook): refaktorer felt-hook i familie-skjema

---

packages/familie-form-elements/package.json
packages/familie-form-elements/src/ja-nei-spørsmål/JaNeiSpørsmål.tsx

Trenger at jaNeiSpm kan ha en annen initiell verdi enn undefined. F.eks. at ja er valgt når den rendres. Dette for å kunne navigere tilbake i søknadsdialog og få opp det man har fylt inn.

fix(Send intiellVerdi som prop): sett en initiell verdi til jaNeiSpm

---

packages/familie-form-elements/package.json
packages/familie-form-elements/src/ja-nei-spørsmål/JaNeiSpørsmål.tsx
packages/familie-form-elements/src/ja-nei-spørsmål/jaNeiSpørsmål.stories.tsx
packages/familie-sprakvelger/package.json

RadioPanelGruppe fra nav-frontend-skjema rendrer feil-kontainer uansett om feil er tom eller ikke.
Skjul alle tomme divs i gruppen for å unngå rar spacing.

fix(familie-form-elements): skjul tom feil-kontainer fra radiopanelgruppe

---

packages/familie-form-elements/src/ja-nei-spørsmål/JaNeiSpørsmål.tsx

Fjern at alle ord får stor forbokstav i labels til ja-nei-spørsmål

fix(Stor eller liten forbokstav): stor forbokstav på kun først ordet

---

packages/familie-skjema/src/felt.ts
packages/familie-skjema/src/skjema.ts
packages/familie-skjema/src/typer.ts

Usikker på hvilke konsekvenser dette får, så vær litt ekstra oppmerksom. Hypotesen er at skjema uansett gir et "visFeilmeldinger" flagg og selv om feltene da initielt blir "feil" så viser man ikke i UI feilmeldinger før "visFeilmeldinger" er true. 
For tilfeller hvor man bruker useFelt alene så bør man uansett håndtere når man skal vise feilmeldinger eksplisitt.

Validerer felt når feltet initialiseres.

---

packages/familie-form-elements/src/datovelger/FamilieDatovelger.tsx

Skjermleser leser ikke opp labelen til datovelgeren. Dette gjør at man ikke vet hva man velger dato for.

Bruk datovelger-input sin id i htmlFor i labelen

---

.eslintrc
packages/familie-sprakvelger/src/Sprakvelger.tsx

Har også fikset eslintrc-fila
Ref https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-hidden_attribute, rent dekorative ikoner kan settes til `aria--hidden="true"`. 
Alternativet er å lage tre nye utility-functions for å få tak i aria label for globe, ned-chevron og opp-chevron på alle støtta språk slik som vi har gjort med dropdown label.
Alternativ to er å bruke intl-objektet nå som vi har intl som peer dependency og gi appen ansvaret for disse tekstene.

fix(språkvelger): gi svger aria-hidden og fjern focusable

---

packages/familie-sprakvelger/sprakvelger.stories.tsx
packages/familie-sprakvelger/src/Sprakvelger.tsx

Gjort språkvelgeren stylebar og fjernet fixed bredde og margin auto slik at apper kan bruke den som
de vil

fix(sprakvelger): fjern 170px bredde på språkvelger

---

packages/familie-form-elements/src/familie-react-select/FamilieReactSelect.tsx

Fjerner visning av knapper/endringikoner under lesevisning
Uten lesevisning 
Med lesevisning **før**
Med lesevisning **etter**
Eksempel fra ba-sak **etter**

Forbedre lesevisning på react multiselect

---

packages/familie-form-elements/package.json
packages/familie-sprakvelger/src/SprakContext.tsx
yarn.lock

affects: @navikt/familie-form-elements, @navikt/familie-sprakvelger
Datovelger med måneder på riktig språk i dropdown
Typer på språkcontext slik at useSpråkContext forteller hva den returnerer

chore(sprakvelger|form-elements): bump datovelgerversjon, typer for språkcontext

---

packages/familie-header/src/header/Header.tsx
packages/familie-header/src/søk/FnrInputWrapper.tsx

Ønsker å kunne linke til personlig side på a-inntekt, med 
```ts
const lagAInntekt = (appEnv: AppEnv, personIdent?: string): PopoverItem => {
if (!personIdent) {
return { name: 'A-inntekt', href: appEnv.aInntekt, isExternal: true };
}
return {
name: 'A-inntekt',
href: '#/a-inntekt',
onClick: (e: React.SyntheticEvent) => {
e.preventDefault();
...
},
};
};
```
Der ... er eks
```ts
preferredAxios
.get(`${appEnv.aInntekt}/api/v2/redirect/sok/a-inntekt`, {
headers: {
'Nav-Personident': personIdent,
},
})
.then((response: AxiosResponse<string>) => {
window.open(response.data);
})
.catch((error: AxiosError<string>) => {
apiLoggFeil(`Henting av redirect-link mot a-inntekt feilet ${error}`);
window.open(appEnv.aInntekt);
});
```

Header linker, lagt til mulighet for override av onClick

---

packages/familie-dokumentliste/dokumentliste.stories.tsx
packages/familie-dokumentliste/src/LogiskeVedlegg.tsx
packages/familie-dokumentliste/src/index.tsx

affects: @navikt/familie-dokumentliste
Lister opp logiske vedlegg (innhold fra skannet dokumenter) under dokumentet.

feat(Dokumentliste): skal vise logiske vedlegg i dokumentliste

---

packages/familie-backend/package.json
packages/familie-backend/src/auth/session.ts
yarn.lock

affects: @navikt/familie-backend
Etter å ha endret prosjektet til type: module, så klager ESlint på at require er brukt i session.ts
i biblioteket familie-backend.

fix(backend): fikset import av connect-redis

---

packages/familie-backend/package.json
yarn.lock

Moment-timezone ser ikke ut til å bli brukt lenger. I tillegg fører den versjonen som var installert til et sikkerhetshull i ba-sak: https://github.com/navikt/familie-ba-sak-frontend/security/dependabot/15.
Sletter derfor hele dependencien. Fint hvis noen med kjennskap til familie-backend tar en titt her, bare for å dobbeltsjekke. Moment-timezone kom opp under unused dependencies (ved å gjøre npx depcheck i familie-backend pakken), men noen ganger er det ikke alltid det stemmer.

Slett moment-timezone fra dependencies

---

packages/familie-dokumentliste/dokumentliste.stories.tsx
packages/familie-dokumentliste/src/LogiskeVedlegg.tsx
packages/familie-dokumentliste/src/index.tsx

affects: @navikt/familie-dokumentliste
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-9268
Mistet litt venstrejustering ved oppdatering til nytt designsystem (Dette ble tidligere lagt på i ef-sak-frontend).
**Før**
**Etter**

fix(dokumentliste): venstrejusterer tekst i dokumentlisten

---

packages/familie-form-elements/package.json
yarn.lock

**Ooops** i #540 fjernet jeg avhengigheter som tilsynelatende ikke var i bruk. Det viser seg at de er peerdependencies for datovelgeren. _Litt_ irriterende at alle CI-actions kjørte grønt på PRen når `yarn build` viste seg å ikke kunne kjøre. Tenker det er på sin plass å legge til et steg i PR-action for det, så vi unngår at noe liknende skjer igjen

fix(familie-form-elements): inkluder fjernede avhengigheter som datovelgeren trenger

---

packages/familie-form-elements/package.json
yarn.lock

Nå med enda flere avhengigheter som `nav-datovelger` ikke opplyser å være avhengig av 🥲  ...nå kjører `yarn build`, `yarn storybook` osv grønt hos meg.

fix(familie-form-elements): legg tilbake enda flere avhengigheter som datovelger trenger

---

packages/familie-form-elements/package.json
yarn.lock

BREAKING CHANGE:
FamilieKnapp mottar nå ikon som prop, se https://aksel.nav.no/designsystem/side/migrering
**Merk også** at vi fra nå av må ha samme versjoner av `ds-css`, `ds-tokens`, `ds-react`. Jeg har konfigurert slik at vi krever samme minor-versjon, også må vi være snille og bytte på å holde familie-felles oppdatert med støtte for nyere minor-versjoner etterhvert som de kommer 🙌

feat(familie-form-elements): oppgrader til v1 av designsystemet

---

packages/familie-form-elements/src/input/FamilieInput.tsx
packages/familie-form-elements/src/input/input.stories.tsx

I det gamle designbiblioteket kunne refs sendes inn som et custom prop og dermed omgå at React behandler `ref`-propen som noe helt eget. Nå som designsystemet forventer å få inn `ref` satt slik React egentlig definerer det, må vi derfor støtte videresending av ref med `React.forwardRef`. Se docs her hvis du vil lese mer: https://reactjs.org/docs/forwarding-refs.html
...eeeegentlig skulle jeg verifisere at FamilieInput aksepterer number som type på value, så jeg har lagt til et eksempel i storybook på en FamilieInput med numerisk verdi og en definert ref som skal videresendes via designsystemets komponent til selve `<input>`-feltet i bunn. Håper det gjør det enklere for nestemann å vite hvordan man går frem 🙂

feat(familie-form-elements): støtt ref forwarding i FamilieInput

---

packages/familie-form-elements/src/datovelger/FamilieDatovelger.tsx
packages/familie-form-elements/src/datovelger/datovelger.stories.tsx

Sjekker også at value har en verdi då dayjs returnerer dagens dato hvis man sender med undefined
BREAKING CHANGE:
valgtDato fjernes og skal nå bruke value
Fortsettelse på
* https://github.com/navikt/familie-felles-frontend/pull/763
Ef-apper:
https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=Tea-10742

feat(FamilieDatoVelger): erstatter bruk av valgtDato med value

---

packages/familie-backend/src/index.ts

Begge disse inneholder Registry.
```
export * from 'openid-client';
export * from 'prom-client';
```
Hva jeg kan se bruker kun Counter fra prom-client, som brukes som argument i `prometheusTellere?: { [key: string]: Counter<string> },`
Virker som at det kun er BA som bruker denne Counter
Publish feiler, vet ikke helt men den har gjort det tidligere også for brancher som jeg har haft canary deploy på 👀

exporterer kun Counter fra prom-client pga conflicting export av Registry

---

packages/familie-endringslogg/package.json

affects: @navikt/familie-endringslogg
BREAKING CHANGE:
@navikt/ds-pakker må installeres i konsumenten
--
En siste bit som hadde falt ut av #822 😇 har testet å kjøre opp storybook hos meg, funket bra

chore(endringslogg): flytt @navikt/ds-pakker til devdeps

---

packages/familie-header/src/søk/Søk.tsx

affects: @navikt/familie-header
Fra v2.2.0 av designsystemet har secondary button transparent bakgrunn https://github.com/navikt/aksel/pull/1789
Så søket vårt, som bruker light mode av [Search](https://aksel.nav.no/komponenter/core/search) ser ganske gyselig ut. Endrer det til å bruke dark mode. Har tatt avsjekk med Gunn

fix(header-søk): bruk dark mode-variant av søk i headeren

---

packages/familie-validering/package.json
yarn.lock

Rydder i avhengighetene til familie-validering.
Så at det var ganske mange pakker som ikke var i bruk, så fjernet disse.
I tillegg, flytter jeg jest til devDependencies og oppgraderer til nyeste versjon

chore(deps): sletter ubrukte dependencies og oppgraderer jest

---

packages/familie-header/package.json
packages/familie-header/src/header/Header.tsx
packages/familie-header/src/søk/Søk.tsx
packages/familie-header/src/søk/useSøk.ts
yarn.lock

- Fjerner avhengigheter i familie-header som ikke er i bruk i pakken eller under bygging
- Skriver oss bort fra `ReactDOM.findDOMNode`, som uansett er deprecated, så vi kan fjerne den avhengigheten
- Setter på noreferrer på eksterne lenker, se eslint-dokumentasjon: https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-no-target-blank.md
Ingen funksjonell eller visuell endring, men legger ved skjermbilder av søkeresultatene ettersom det er popoveren jeg har påvirket mest direkte med omskrivingen
Før:
Etter:

Rydd opp i avhengigheter i header + minirefactor

---

packages/familie-backend/src/auth/session.ts
packages/familie-backend/src/typer.ts

Skal legge til rette for å kunne kjøre Aiven Redis istedenfor "hjemmesnekra" redis-oppsett.
Fordelen med dette er at det skal være nedetidsfri oppdatering slik at saksbehandlere ikke blir "kastet ut" av løsningene hver gang nais-teamet kjører oppgradering på tvers og restarter applikasjoner. 
For å bruke redis med aiven må man sende inn parametrene 
```
redisFullUrl
redisBrukernavn
redisPassord
```
Man skal _IKKE_ sende inn `redisUrl` hvis man ønsker å bruke Aiven Redis. 
Alt er bakoverkompatibelt og støtter selvsagt bruk av den gamle redisløsningen da vi ikke klarer å skrive oss bort fra dette med det første. 
[Les mer her om hvordan man setter opp Aiven Redis for en applikasjon](https://docs.nais.io/persistence/redis/?h=redis)

Redis med aiven

---

packages/familie-clipboard/package.json
packages/familie-datovelger/package.json
packages/familie-dokumentliste/package.json
packages/familie-endringslogg/package.json
packages/familie-form-elements/package.json
packages/familie-header/package.json
packages/familie-header/src/header/Header.tsx
packages/familie-header/src/søk/Søk.tsx
packages/familie-sprakvelger/package.json
packages/familie-tidslinje/package.json
packages/familie-visittkort/package.json
yarn.lock

Komponenter i ds-react-internal er flyttet over til ds-react. Oppgraderer derfor til nyeste ds-pakker som har dette, samt fjerner internal-pakkene.
Testet ved å ta inn alpha-versjonen i ba-sak-frontend lokalt, og der ser alt fint ut.
Skjermbilder av ny versjon:

støtt v4 av designsystemet

---

packages/familie-clipboard/README.md
packages/familie-visittkort/package.json
packages/familie-visittkort/src/index.tsx
yarn.lock

Et skritt på veien for å fjerne familie-clipboard (Aksel har en komponent som erstatter denne, unødvendig å holde denne pakken oppdatert)
- Bytter ut familie-clipboard med CopyButton fra Aksel i familie-visittkort. Det er noen visuelle forskjeller, se bilder under. Men dette står i stil til andre kopier-knapper i løsningene våre/til nav. Se eksempel på bruk her: https://aksel.nav.no/komponenter/core/copybutton. OBS! Det er en breaking change på familie-visittkort som nå krever ds-pakker versjon 4 (altså er ikke v2 og v3 lenger tillatt, fordi vi trenger en komponent som kun er i v4+)
- Skriver i readme til familie-clipboard at denne komponenten er deprecated
Før
Etter

Gjør familie-clipboard deprecated

---

packages/familie-visittkort/src/index.tsx

Fiks bug jeg innførte her: https://github.com/navikt/familie-felles-frontend/pull/1144/files
Kopiert ident har tidligere fått filtrert vekk mellomrom. Legger tilbake dette. 
Kan diskutere om dette er beste måten å løse det på. Burde man heller gjøre motsatt - sende inn ikke-formattert ident og heller formattere den for visning frontend? Dumme med det er at alle må endre koden, så dette var minste motstands vei fordi ingen må gjøre oppdatering i koden annet enn å ta i bruk nyeste versjon av familie-visittkort.

fix(familie-visittkort): sørger for at kopiert ident ikke er formattert

---

packages/familie-sprakvelger/package.json
packages/familie-sprakvelger/sprakvelger.stories.tsx
packages/familie-sprakvelger/src/SprakContext.tsx
packages/familie-sprakvelger/src/Sprakvelger.tsx
packages/familie-sprakvelger/src/SpråkSelectMenu.tsx
yarn.lock

Fjerner alt som har med react-intl å gjøre i denne pakken. Dette må flyttes ut i konsumentene. Oppgraderer til aksel v5 og react 18.
BREAKING CHANGE: IntlProvider er fjernet og må implementeres i konsumenten. Krever aksel v5 og react 18.

familie-sprakvelger: Bytter ut ds-icons og fjerner IntlProvider

---

package.json
yarn.lock

Gikk ikke lenger å bruke `yarn ct` etter oppgradering av lerna. Bytter ut `cz-lerna-changelog` med `cz-conventional-changelog` som funker på nesten samme måte som før for å få riktig formatterte commit-meldinger. 
Daphne har testet å publisere pakker på denne måten og det funket veldig bra :D

chore(package.json): oppgraderer fra cz-lerna-changelog til cz-conventional-changelog

---

packages/familie-datovelger/package.json
packages/familie-endringslogg/package.json
packages/familie-form-elements/package.json
packages/familie-form-elements/src/lesefelt/FamilieLesefelt.tsx
packages/familie-header/package.json
packages/familie-visittkort/package.json
yarn.lock

Tillater Aksel v5 i flere av pakkene våre. Fjerner støtte for Aksel v2 og v3.
I aksel v5 har BodyShort fått størrelsen "large" som ikke er mulig å bruke på "Label". Skriver derfor heller manuelt ut størrelsen på FamilieLesefelt. Ønsker ikke at "large" skal være en mulighet så lenge ikke begge komponentene kan være den størrelsen. 
BREAKING CHANGE: Funker ikke lenger med aksel v2 og v3

Tillater Aksel v5 i flere pakker

---

packages/familie-sprakvelger/package.json
yarn.lock

Versjonen av familie-form-elements som ble bruk i språkvelgeren var ikke oppdatert til å håndtere versjon 5 av aksel (som er det språkvelgeren var oppdatert til å bruke)

feat(familie-sprakvelger): oppgraderer familie-form-elements som nå tillater aksel v5

---

packages/familie-backend/src/auth/authenticate.ts
packages/familie-backend/src/auth/bruker.ts
packages/familie-backend/src/router.ts
packages/familie-backend/src/utils.ts

For å unngå at saksbehandlere havner i en tilstand med "ukjent enhet", ingen brukerdata og følgelig ingen grupper (som gjerne defaulter til veiledervisning i saksbehandlingsløsningen) har vi gjort noen endringer. 
1. Tatt bort at man setter tom bruker på sesjonen med "9999" i enhet, men heller kjører igjennom uten bruker dersom det feiler mot MS.
2. Lagt inn slik at man har en retry mot MS før løsningen feiler
3. Trekker ut kall mot MS til profil-endepunktet - og ikke ALLE kall mot backend. Det er kun her vi har behov for denne informasjonen.
Gotcha: Ikke kast feil uten å håndtere de i node express - da krasjer appen og dør ☠️

Bedre feilhåndtering av kall mot MS for brukerdata

---

packages/familie-datovelger/package.json
packages/familie-dokumentliste/package.json
packages/familie-endringslogg/package.json
packages/familie-form-elements/package.json
packages/familie-header/package.json
packages/familie-ikoner/package.json
packages/familie-logging/package.json
packages/familie-skjema/package.json
packages/familie-sprakvelger/package.json
packages/familie-tidslinje/package.json
packages/familie-tidslinje/src/components/tidslinje/Tidslinje.tsx
packages/familie-tidslinje/src/components/tidslinje/TimelinePeriod.tsx
packages/familie-tidslinje/src/components/tidslinje/TimelineRow.tsx
packages/familie-validering/package.json
packages/familie-visittkort/package.json
yarn.lock

Fjernet støtte for react 17, nav sitt designbibliotek v.4 og eldre, samt lagt inn støtte for å bruke styled-components versjon 6. familie-tidslinje brukte en gammel implementasjon av styled props, som måtte skrives om
BREAKING CHANGE: Fjernet støtte for react 17 og nav ds <=4

chore(alle komponenter): oppdatert avhengigheter til alle komponenter

---

packages/familie-ikoner/ikoner.stories.tsx
packages/familie-visittkort/package.json
packages/familie-visittkort/src/index.tsx
packages/familie-visittkort/visittkort.stories.tsx

Tar i bruk komponenten [HStack fra Aksel](https://aksel.nav.no/komponenter/primitives/hstack) for å løse layouten i familie-visittkort, og legger til et utvidet eksempel på bruk av FamilieVisittkort
Legger til props for å ha en dempet farge på kantlinjen i bunnen ([se kantlinjefarger i Aksel](https://aksel.nav.no/grunnleggende/styling/design-tokens#adb1767e2f87)) samt padding på sidene av visittkortet
Det blir en `BREAKING CHANGE` i familie-visittkort pga endring av props-interface og layoutprinsipper da vi går over til flexbox med fastsatt`gap` heller enn den tidligere løsningen der konsumenten gjerne måtte sette marginverdier på hvert barneelement
Legger også til et eksempel på ikon for ukjent kjønn i dokumentasjonen til FamilieIkonVelger, men dette påvirker ikke selve pakken.
<details> …

Feat/oppgrader FamilieVisittkort

---

packages/familie-http/src/HttpProvider.tsx

Fra v2 til v3 i constate så er det endringer i måten man bruker den på, uten at dette er implementert hos oss. Se: https://github.com/diegohaz/constate/blob/bbad5665d124c64f71cadbd6ad44d95a96b02d4d/CHANGELOG.md?plain=1#L57

fix(familie-http): retter opp måten vi bruker constate på slik at det stemmer med dokumentasjon

---

packages/familie-endringslogg/src/endringslogg.css

Tidligere var bare backgrunnsfargen satt, men ikke tekstfargen. Hvis man da feks brukte endringsloggen i en komponent som setter tekstfargen til hvit (feks internal header i aksel) blir teksten hvit, og usynlig mot bakgrunnen.
Ser ellers likt ut i storybook.

style(endringslogg): bruk akselfarger for bakgrunn og tekst

---

packages/familie-header/src/søk/Søkeresultat.tsx

…tat element
Ønsker at elementet skal ha lik border radius som parent element sånn at hjørnene ikke synes over.
Liste:
Gammel:
NY:

Border radius resultat element

---

packages/familie-http/src/axios.ts

Får denne feilen når jeg prøver å bruke siste versjon av familie-skjema i ba-sak-frontend:
Ser ut som det skyldes måten man importerer Sentry på fra @sentry/core, så prøver dette

fix(familie-http, familie-skjema): fikser syntaks på sentry-bruk så vi ikke får byggfeil

---

packages/familie-header/header.stories.tsx
packages/familie-header/src/header/Header.tsx

Vi ønsker å legge på mer info i brukers dropdown. Per [Aksel](https://aksel.nav.no/komponenter/core/i-header#headerdemo-brukermeny) har vi mulighet til å også legge med tekstinnhold. Slik eksempelet er i Aksel ligger denne infoen på toppen, som jeg synes gir veldig mening i den konteksten.
Jeg har dermed valgt å legge til en ny prop `popoverDetail`. Denne legger seg alltid på toppen hvis den finnes. Alt ser ut som før hvis denne ikke inkluderes, som tilrettelegger for en smooth minor upgrade. 😊 
----
Skjermbilde fra Storybook med `popoverDetail`:
---
Skjermbilde fra Storybook uten `popoverDetail`, da ser alt ut som før:

Kan vise ekstra info i brukers dropdown før lenkene i Header

---

packages/familie-endringslogg/package.json
packages/familie-endringslogg/src/transition-container.tsx
yarn.lock

Må fjerne transition-bibliotek pga feilsituasjoner i react 18 - og det hele kan løses med css
BREAKING CHANGE: Bumpet til react 19

fix(familie-endringslogg): feilende transition-bibliotek

---

packages/familie-header/header.stories.tsx
packages/familie-header/src/header/Header.tsx
packages/familie-ikoner/src/familie/EksternLinkIkon.tsx
packages/familie-ikoner/src/familie/index.ts

Lagt til optional property på header, denne brukes slik at label "Lenker" vises over eksterne lenker, samt ikoner foran lenker.
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-24000)
Uten:
Med:

feat(header): mulighet for visning av label og ikon på header

---

packages/familie-http/src/axios.ts
packages/familie-typer/src/ressurs.ts

Vi legger til callId i ressurs objektet og legger det til i frontend meldinga hvis den finnes.
Ved bruk av ny familie-felles-frontend versjon + oversending av callId fra backend vil det se sånn her ut ved feil:

Vi legger til callId i ressurs objektet og legger det til i frontend meldinga hvis den finnes meldinga hvis den finnes

---

packages/familie-header/header.stories.tsx
packages/familie-header/src/header/Header.tsx

Lenker i Header skal støtte flere ikoner
BREAKING CHANGE: Trenger ikke lenger sende inn skalViseLabelsOgIkonPåLenker for å vise ikoner og underoverskrifter. Nå angir man dette via den nye propen lenkeType på PopoverItem

feat(header.tsx): lenker i Header skal støtte flere ikoner

---

packages/familie-http/package.json
packages/familie-http/src/HttpProvider.tsx
yarn.lock

BREAKING CHANGE: useHttp må nå alltid brukes inni en HttpProvider. Går vekk fra constate og skriver oss om til en React-context med en egen Provider-komponent og en egen hook.
Jeg har sjekket og tror ikke dette er en breaking change for noen siden alle løsningene jeg sjekket allerede wrapper alt i en `HttpProvider`. Da er det ingen endringer som må gjøres for å ta denne versjonen i bruk. Men teoretisk sett kan det bli breaking change for noen hvis løsningen ikke wrappes med `HttpProvider` fra før av. 
Tenkte uansett det er fint å si ifra i tilfelle denne oppdateringen feiler for noen. ☺️

Fjerner constate, useHttp må nå alltid brukes inni en HttpProvider

---

packages/familie-backend/package.json
packages/familie-endringslogg/package.json
packages/familie-form-elements/package.json
packages/familie-header/package.json
packages/familie-http/package.json
packages/familie-ikoner/package.json
packages/familie-logging/package.json
packages/familie-skjema/package.json
packages/familie-tidslinje/package.json
packages/familie-typer/package.json
packages/familie-typer/tsconfig.json
packages/familie-visittkort/package.json
tsconfig.base.json
yarn.lock

Siden Node 18 er [filendelser i import-statements nå obligatoriske for ES-moduler](https://nodejs.org/dist/latest-v18.x/docs/api/esm.html#esm_mandatory_file_extensions). Denne pakken fikser slik at vi får riktige filendelser i de byggede filene våre.
Endringen er rett og slett slik (eksempel fra familie-typer sin byggede index.js):
````
export * from './person.js';
export * from './oppgave.js';
export * from './saksbehandler.js';
export * from './ressurs.js';
export * from './journalføring.js';
//# sourceMappingURL=index.js.map
````
I stedet for den gamle koden:
````
export * from './person';
export * from './oppgave';
export * from './saksbehandler';
export * from './ressurs';
export * from './journalføring';
//# sourceMappingURL=index.js.map
````
Jeg fant problemet når jeg prøvde å …

Fiks filendelser for ES-moduler (ESM)
